### PR TITLE
[CVP-3985] Add spec.skips to parsed_operator_data

### PR DESCRIPTION
**Pull request by yashvardhannanavati**

### CODE REVIEW

**Comment by yashvardhannanavati** [comment]
@asergienk  @nmars @samvarankashyap Could you please help take a look? 

P.S: The CI seems to be failing on something unrelated to this change. Please correct me if I am mistaken

**Comment by lslebodn** [comment]
> @asergienk @nmars @samvarankashyap Could you please help take a look?
> 
pyxis just return different error message. it shodul eb trivial to fix it in the same PR but different commit message

**Comment by yashvardhannanavati** [comment]
> > @asergienk @nmars @samvarankashyap Could you please help take a look?
> 
> pyxis just return different error message. it shodul eb trivial to fix it in the same PR but different commit message

fixed it in #459

**Pull request merged**
