### PR TITLE
Parse OpenShift subscription annotation from CSV

### PR DESCRIPTION
**Pull request by nmars**
Added code to parse `operators.openshift.io/valid-subscription` from CSV annotations.

### CODE REVIEW

**Comment by nmars** [comment]
My previous (reverted) pull request had an incorrect filter at line 113 in `roles/parse_operator_bundle/tasks/main.yml`

The previous PR had `| default([])`

So if a value was present in the CSV ansible would parse it as a string instead of a list.

The parsed_operator_data.j2 would then split the string and print something like:

```
operator_valid_subscription:
  - "["
  - """
  - "O"
  - "p"
  - "e"
  - "n"
  - "S"
  - "h"
  - "i"
  - "f"
  - "t"
  - " "
...
```

The current PR corrects this.

**Comment by lslebodn** [comment]
It would be nice to write some tests in upstream.
* https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/blob/master/Dockerfiles/ci/run_tests.py

Ideally for case without required annotation and with them.

**Comment by nmars** [comment]
Tests added.

**Comment by lslebodn** [comment]
> Tests added 

Thank you very much.

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
